"""add column category to bids

Revision ID: 9a1ee025e55d
Revises: c49e3af83286
Create Date: 2017-04-25 05:47:51.040737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1ee025e55d'
down_revision = 'c49e3af83286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bids', 'category')
    # ### end Alembic commands ###
