"""added column categories

Revision ID: bd1182b81146
Revises: b73811be5f44
Create Date: 2017-04-23 06:01:50.631106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1182b81146'
down_revision = 'b73811be5f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bids', 'category')
    # ### end Alembic commands ###
